var tags = [

{name: 'Hiring Day',label: 'Are you participating in the [May 20th] Hiring Day?',type: 'binary',position: 1,active: true,isPublic: true,category: 'Job Search'},
{name: 'US Citizen',label: 'Are you a U.S. citizen?',type: 'binary',position: 2,active: true,isPublic: true,category: 'Job Search'},
{name: 'Locations of Interest',label: 'What other cities, if any, are you open to?',type: 'text',position: 3,active: true,isPublic: true,category: 'Job Search'},
{name: 'Other (Job Search)',label: 'Anything else we should know about your job search situation?',type: 'text',position: 4,active: true,isPublic: true,category: 'Job Search'},
{name: 'San Francisco',label: 'I want to work in San Francisco',type: 'scale',position: 1,active: true,isPublic: true,category: 'Location'},
{name: 'Peninsula',label: 'I want to work in the Peninsula (e.g. Redwood City)',type: 'scale',position: 2,active: true,isPublic: true,category: 'Location'},
{name: 'South Bay',label: 'I want to work in the South Bay (e.g. Mountain View)',type: 'scale',position: 3,active: true,isPublic: true,category: 'Location'},
{name: 'East Bay',label: 'I want to work in the East Bay (e.g. Oakland)',type: 'scale',position: 4,active: true,isPublic: true,category: 'Location'},
{name: 'Remote / At Home',label: 'I want to work at home (as part of a distributed team)',type: 'scale',position: 5,active: true,isPublic: true,category: 'Location'},
{name: 'SPA / Front-End',label: 'Single Page App Architect (front end through & through)',type: 'scale',position: 1,active: true,isPublic: true,category: 'Role'},
{name: 'UI/UX',label: 'UI/UX Artist (cares about whitespace, pixel perfection and slick interactions)',type: 'scale',position: 2,active: true,isPublic: true,category: 'Role'},
{name: 'Systems Architect',label: 'Systems Architect & Data Structures Guru',type: 'scale',position: 3,active: true,isPublic: true,category: 'Role'},
{name: 'Data Viz',label: 'Data Viz Nerd (loves d3)',type: 'scale',position: 4,active: true,isPublic: true,category: 'Role'},
{name: 'Big Data',label: 'Big Data Processing Badass (likes hadoop, machine learning, etc)',type: 'scale',position: 5,active: true,isPublic: true,category: 'Role'},
{name: 'Product Manager',label: 'Product Manager (engineer who gets his/her kicks from thinking about product / UX)',type: 'scale',position: 6,active: true,isPublic: true,category: 'Role'},
{name: 'Full Stack',label: 'Full-stack Generalist',type: 'scale',position: 7,active: true,isPublic: true,category: 'Role'},
{name: 'Testing',label: 'Stickler for Testing ',type: 'scale',position: 8,active: true,isPublic: true,category: 'Role'},
{name: 'Feynman',label: 'Feynman: Solves Complex Problems in Any Language',type: 'scale',position: 9,active: true,isPublic: true,category: 'Role'},
{name: 'Design-gineer',label: 'Design-gineer (comfortable and capable with Photoshop but can also turn mockups into functional prototypes)',type: 'scale',position: 10,active: true,isPublic: true,category: 'Role'},
{name: 'Exciting Industries',label: 'What industries / domains excite you the most?',type: 'text',position: 11,active: true,isPublic: true,category: 'Role'},
{name: 'Other (Role)',label: 'What else should we know about the role you are looking for or the work you like doing?',type: 'text',position: 12,active: true,isPublic: true,category: 'Role'},
{name: 'Engineer #1',label: 'Being engineer #1 or #2 at a small but awesome startup.  Lower base salary, more equity',type: 'scale',position: 1,active: true,isPublic: true,category: 'Company Size'},
{name: 'Mid-Size Company',label: 'Being part of mid-sized engineering team in a mid-sized company',type: 'scale',position: 2,active: true,isPublic: true,category: 'Company Size'},
{name: 'Large Company',label: 'Being part of a very large company',type: 'scale',position: 3,active: true,isPublic: true,category: 'Company Size'},
{name: 'Consultant',label: 'Working with customers as part of an engineering consultancy',type: 'scale',position: 4,active: true,isPublic: true,category: 'Company Size'},
{name: 'Sales Engineer',label: 'Working with customers in a client success or sales engineer role',type: 'scale',position: 5,active: true,isPublic: true,category: 'Company Size'},
{name: 'Product Manager',label: 'Leading product definition and defining user experience',type: 'scale',position: 1,active: true,isPublic: true,category: 'Recent Experience'},
{name: 'Performance / Scability',label: 'Optimizing your work for performance and scalability',type: 'scale',position: 2,active: true,isPublic: true,category: 'Recent Experience'},
{name: 'Algorithms',label: 'Writing algorithms',type: 'scale',position: 3,active: true,isPublic: true,category: 'Recent Experience'},
{name: 'Data Structures',label: 'Designing data structures',type: 'scale',position: 4,active: true,isPublic: true,category: 'Recent Experience'},
{name: 'Data Science',label: 'Doing data science related activities',type: 'scale',position: 5,active: true,isPublic: true,category: 'Recent Experience'},
{name: 'APIs',label: 'Considering only your recent projects / work, how much time did you directly spend. integrating APIs',type: 'scale',position: 6,active: true,isPublic: true,category: 'Recent Experience'},
{name: 'TDD',label: 'Doing test driven development (TDD)',type: 'scale',position: 7,active: true,isPublic: true,category: 'Recent Experience'},
{name: 'UI/UX',label: 'UI/UX',type: 'scale',position: 1,active: true,isPublic: true,category: 'Skills'},
{name: 'CSS',label: 'CSS',type: 'scale',position: 2,active: true,isPublic: true,category: 'Skills'},
{name: 'Bootstrap',label: 'Bootstrap',type: 'scale',position: 3,active: true,isPublic: true,category: 'Skills'},
{name: 'jQuery',label: 'jQuery',type: 'scale',position: 4,active: true,isPublic: true,category: 'Skills'},
{name: 'AJAX',label: 'AJAX',type: 'scale',position: 5,active: true,isPublic: true,category: 'Skills'},
{name: 'Angular',label: 'Angular',type: 'scale',position: 6,active: true,isPublic: true,category: 'Skills'},
{name: 'Backbone',label: 'Backbone',type: 'scale',position: 7,active: true,isPublic: true,category: 'Skills'},
{name: 'Ember',label: 'Ember',type: 'scale',position: 8,active: true,isPublic: true,category: 'Skills'},
{name: 'Node/Express',label: 'Node/Express',type: 'scale',position: 9,active: true,isPublic: true,category: 'Skills'},
{name: 'CoffeeScript',label: 'CoffeeScript',type: 'scale',position: 10,active: true,isPublic: true,category: 'Skills'},
{name: 'D3',label: 'D3',type: 'scale',position: 11,active: true,isPublic: true,category: 'Skills'},
{name: 'Grunt',label: 'Grunt',type: 'scale',position: 12,active: true,isPublic: true,category: 'Skills'},
{name: 'Gulp',label: 'Gulp',type: 'scale',position: 13,active: true,isPublic: true,category: 'Skills'},
{name: 'Git',label: 'Git',type: 'scale',position: 14,active: true,isPublic: true,category: 'Skills'},
{name: 'R',label: 'R',type: 'scale',position: 15,active: true,isPublic: true,category: 'Skills'},
{name: 'Matlab',label: 'Matlab',type: 'scale',position: 16,active: true,isPublic: true,category: 'Skills'},
{name: 'MySQL',label: 'MySQL',type: 'scale',position: 17,active: true,isPublic: true,category: 'Skills'},
{name: 'PostGres',label: 'PostGres',type: 'scale',position: 18,active: true,isPublic: true,category: 'Skills'},
{name: 'MongoDB',label: 'MongoDB',type: 'scale',position: 19,active: true,isPublic: true,category: 'Skills'},
{name: 'HTML',label: 'HTML',type: 'scale',position: 20,active: true,isPublic: true,category: 'Skills'},
{name: 'Wordpress',label: 'Wordpress',type: 'scale',position: 21,active: true,isPublic: true,category: 'Skills'},
{name: 'Python',label: 'Python',type: 'scale',position: 22,active: true,isPublic: true,category: 'Skills'},
{name: 'C / C++',label: 'C / C++',type: 'scale',position: 23,active: true,isPublic: true,category: 'Skills'},
{name: 'Neo4j',label: 'Neo4j',type: 'scale',position: 24,active: true,isPublic: true,category: 'Skills'},
{name: 'Azure',label: 'Azure',type: 'scale',position: 25,active: true,isPublic: true,category: 'Skills'},
{name: 'AWS',label: 'AWS',type: 'scale',position: 26,active: true,isPublic: true,category: 'Skills'},
{name: 'Firebase',label: 'Firebase',type: 'scale',position: 27,active: true,isPublic: true,category: 'Skills'},
{name: 'Java',label: 'Java',type: 'scale',position: 28,active: true,isPublic: true,category: 'Skills'},
{name: 'Ionic',label: 'Ionic',type: 'scale',position: 29,active: true,isPublic: true,category: 'Skills'},
{name: 'Flash',label: 'Flash',type: 'scale',position: 30,active: true,isPublic: true,category: 'Skills'},
{name: 'PhoneGap',label: 'PhoneGap',type: 'scale',position: 31,active: true,isPublic: true,category: 'Skills'},
{name: 'Karma',label: 'Karma',type: 'scale',position: 32,active: true,isPublic: true,category: 'Skills'},
{name: 'Protactor',label: 'Protactor',type: 'scale',position: 33,active: true,isPublic: true,category: 'Skills'},
{name: 'TDD',label: 'TDD',type: 'scale',position: 34,active: true,isPublic: true,category: 'Skills'},
{name: 'Jasmine / Mocha',label: 'Jasmine / Mocha',type: 'scale',position: 35,active: true,isPublic: true,category: 'Skills'},
{name: 'LESS / SASS/ Stylus',label: 'LESS / SASS/ Stylus',type: 'scale',position: 36,active: true,isPublic: true,category: 'Skills'},
{name: 'Private User Tag 1', label: 'PUT1', type: 'scale', position: 37, active: true, isPublic: false, category: 'Private User Tags'},
{name: 'Private User Tag 2', label: 'PUT2', type: 'scale', position: 38, active: true, isPublic: false, category: 'Private User Tags'},
{name: 'Private User Tag 3', label: 'PUT3', type: 'scale', position: 39, active: true, isPublic: false, category: 'Private User Tags'},
{name: 'Private User Tag 4', label: 'PUT4', type: 'scale', position: 40, active: true, isPublic: false, category: 'Private User Tags'},
{name: 'Private User Tag 5', label: 'PUT5', type: 'scale', position: 41, active: true, isPublic: false, category: 'Private User Tags'},
{name: 'Private User Tag 6', label: 'PUT6', type: 'scale', position: 42, active: true, isPublic: false, category: 'Private User Tags'},
{name: 'Private User Tag 7', label: 'PUT7', type: 'scale', position: 43, active: true, isPublic: false, category: 'Private User Tags'}
];

module.exports = exports = tags;
